In [ ]:
import torch

In [ ]:
#학습 데이터 생성
#y = 2x + 3x - 4
x_train = torch.FloatTensor([[1, 2], [3, 2], [3, 7], [1, 1], [1, 0]])
y_train = torch.FloatTensor([[4],[8],[23], [1], [-2]])

#w,b 초기화 및 Learning rate 설정
w = torch.randn(2, 1)
b = torch.randn(1, 1)
print(w)
print(b)
lr = 0.01

#반복 횟수 설정 및 requires_grad를 True로 설정
for epoch in range(3001):
  w.requires_grad_(True)
  b.requires_grad_(True)

  h = x_train @ w + b
  cost = ((h - y_train) ** 2).mean() # 평균

  #기울기 계산 및 w,b 업데이트
  cost.backward()
  with torch.no_grad(): #이미 계산한 기울기를 가지고 업데이트 하는 것이라 no_grad
    w = w - lr * w.grad
    b = b - lr * b.grad #b.grad -> cost를 b로 미분했을 때

    if epoch % 100 == 0:
      print('epoch: {}, cost: {:.6f}, w: {}, b: {}'.format(epoch, cost.item(), w.squeeze(), b))


tensor([[-0.2568],
        [ 0.5247]])
tensor([[-1.1198]])
epoch: 0, cost: 110.173622, w: tensor([0.1261, 1.2316]), b: tensor([[-0.9774]])
epoch: 100, cost: 0.995037, w: tensor([0.8296, 3.1655]), b: tensor([[-1.8859]])
epoch: 200, cost: 0.503236, w: tensor([1.1098, 3.1559]), b: tensor([[-2.5198]])
epoch: 300, cost: 0.258518, w: tensor([1.3561, 3.1160]), b: tensor([[-2.9429]])
epoch: 400, cost: 0.132856, w: tensor([1.5377, 3.0836]), b: tensor([[-3.2426]])
epoch: 500, cost: 0.068277, w: tensor([1.6685, 3.0600]), b: tensor([[-3.4571]])
epoch: 600, cost: 0.035089, w: tensor([1.7624, 3.0430]), b: tensor([[-3.6108]])
epoch: 700, cost: 0.018033, w: tensor([1.8296, 3.0308]), b: tensor([[-3.7210]])
epoch: 800, cost: 0.009267, w: tensor([1.8779, 3.0221]), b: tensor([[-3.8000]])
epoch: 900, cost: 0.004763, w: tensor([1.9124, 3.0158]), b: tensor([[-3.8566]])
epoch: 1000, cost: 0.002448, w: tensor([1.9372, 3.0114]), b: tensor([[-3.8972]])
epoch: 1100, cost: 0.001258, w: tensor([1.9550, 3.0081]), b:

In [ ]:
# 새로운 데이터를 넣어 결과 확인
x_test = torch.FloatTensor([[5, 10]])
y_test = x_test @ w + b
print(y_test)

tensor([[35.9998]])


In [4]:
#Sklearn을 활용한 Linear Regression
from sklearn.linear_model import LinearRegression
import pandas as pd

train = pd.read_csv('linear_regression_data_1.csv')
perch_full = train.to_numpy()
print(perch_full)
lr = LinearRegression() # 모델 생성
lr.fit(x, y) # 학습(피팅)

print(lr.coef_,lr.intercept_) # w, b
print(lr.predict([[5, 10]])) # 예측 결과

[[ 1.16895212e+00  1.11123573e+00 -2.28011058e-02 -1.16839341e+00
   9.28357208e-01 -3.31052283e-01 -1.34735270e+00  2.02100830e+00
   9.00160140e+00]
 [ 2.35191578e-01  3.20886199e-01  1.81305510e-02 -8.10770521e-03
   3.04187479e-01  1.37488815e+00  1.04095526e+00  1.06496114e+00
  -2.49532816e+00]
 [ 1.01528862e+00 -1.08768934e-01  5.19113353e-01  1.50502235e+00
  -9.40099468e-01  1.72221403e+00 -4.96833930e-01 -8.72858422e-01
  -1.14044200e+01]
 [ 1.63966917e-01 -7.49437152e-01  5.58106792e-01 -2.22127541e-01
  -8.01443613e-01 -8.88988548e-01 -1.67593875e+00 -7.78945220e-03
   8.58396326e+00]
 [-2.76140024e-01  4.65290008e-01 -3.07913523e-01  1.54243495e+00
  -9.96871202e-01  2.13997171e-01  1.95465080e-01 -2.56213959e-01
  -2.24763688e-01]
 [ 8.37760933e-01 -6.63606749e-01  1.58665515e-01  2.17200351e+00
   8.31740862e-01  1.14428073e+00 -1.66592942e+00  1.17847481e+00
   1.88080868e+01]
 [-2.59642263e-01  7.86623989e-01 -3.45237197e-01 -9.61240020e-01
  -7.78082782e-01 -1.8244305