In [40]:
import torch

In [41]:
#텐서 만들기
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("x = ", x)
print("type =", x.type())
print("y = ", y)

x =  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
type = torch.LongTensor
y =  tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [ ]:
#크기와 랭크(차원) 확인하기
#size와 shape은 동일한 기능, shape을 보통 더 많이 사용
#ndimension 보단 보통 len(shape())을 더 많이 사용
print("Size =", x.size())
print("Shape =", x.shape)
print("Rank =", x.ndimension())

Size = torch.Size([3, 3])
Shape = torch.Size([3, 3])
Rank = 2


In [ ]:
#텐서 모양 바꾸기

#unsqueeze(x,i): tensor x에 i번째 차원
#영상의 모양 바뀌는 거 참고
x0 = torch.unsqueeze(x, 0)
x1 = torch.unsqueeze(x, 1)
x2 = torch.unsqueeze(x, 2)

print(x0.shape)
print(x1.shape)
print(x2.shape)

print(x)
print(x0)
print(x1)
print(x2)


torch.Size([1, 3, 3])
torch.Size([3, 1, 3])
torch.Size([3, 3, 1])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])


In [ ]:
#squeeze(x): 텐서 x에서 크기가 1인 차원 제거
#불필요한 차원 제거
x3 = torch.squeeze(x0)
print(x3.shape)
print(x3)

xt = x.unsqueeze(0).unsqueeze(1).unsqueeze(0).unsqueeze(5)
print(xt.shape)
xt = torch.squeeze(xt)
print(xt.shape)

torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([1, 1, 1, 3, 3, 1])
torch.Size([3, 3])


In [ ]:
#x.view([shape]): x를 [shape]의 모양으로 변화
x4 = x.view(9)
x5 = x.view(1,3,3)
print(x)
print(x4)
print(x5)

print(x.view(3, -1))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])


In [ ]:
#행렬 연산
#xw + b
x = torch.FloatTensor([[1,2], [3, 4], [5, 6]]) # 3 x 2
w = torch.randn(1,2, dtype=torch.float) # 2 x 1
b = torch.randn(3,1, dtype=torch.float)

print(torch.mm(x, torch.t(w)) + b)#torch.t(w) == w.T

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[-0.5458, -0.0028]])
tensor([[ 0.5214],
        [-1.0319],
        [ 1.8176]])
tensor([[-0.0301],
        [-2.6809],
        [-0.9288]])


In [ ]:
#Autograd: 기울기 계산
#requires_grad: 기울기 계산 여부

# l = a^2 = (3w)^2 = 9w^2
#
w = torch.tensor(1.0, requires_grad=True)
a = w*3
l = a**2
l.backward() # 미분
print('l을 w로 미분한 값은',w.grad) # grad - 기울기 저장

l을 w로 미분한 값은 tensor(18.)
